default_context:
  project_name: 'you'
  project_slug: 'youbot'
  domain_main: 'youbot.com'
  domain_staging: 'stag.youbot.com'
  docker_swarm_stack_name_main: 'youbot-com'
  docker_swarm_stack_name_staging: 'stag-youbot-com'
  secret_key: '29fff9ff10725074c72e4460c85fb7ba2b9bccce63828d729bc2a23fd66117d1'
  first_superuser: 'admin@youbot.com'
  first_superuser_password: 'admin'
  backend_cors_origins: 'http://localhost, http://localhost:4200, http://localhost:3000, http://localhost:8080, https://localhost, https://localhost:4200, https://localhost:3000, https://localhost:8080, http://dev.youbot.com, https://stag.youbot.com, https://youbot.com, http://local.dockertoolbox.tiangolo.com, http://localhost.tiangolo.com'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@youbot.com'
  postgres_password: 'postgres'
  pgadmin_default_user: 'admin@youbot.com'
  pgadmin_default_user_password: 'pgadmin'
  traefik_constraint_tag: 'youbot.com'
  traefik_constraint_tag_staging: 'stag.youbot.com'
  traefik_public_network: 'traefik-public'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:admin'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
